# Generated by Django 4.2.6 on 2024-07-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
